Add package.json
This is required for two reasons:

- When using SCSS/SASS, Hugo Pipe’s PostCSS requires the postcss-cli JavaScript package to be installed in the environment

- When a package-lock.json file is found when deploying to Azure Static Web Apps Preview, the deployment fails with the following error:

Error: Could not find either 'build' or 'build:azure' node under 'scripts' in package.json. Could not find value for custom run build command using the environment variable key 'RUN_BUILD_COMMAND'.Could not find tools for building monorepos, no 'lerna.json' or 'lage.config.js' files found.